apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-nginx
  namespace: homework
data:
  default.conf: |
    server {
      listen 8000 default_server;
      server_name _;
      default_type text/plain;
      location / {
        root /homework;
        index index.html index.htm;
      }
      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
      root /usr/share/nginx/html;
      }
    }