apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: nc
              mountPath: /etc/nginx/conf.d/status.conf
              subPath: status.conf
        - image: nginx/nginx-prometheus-exporter:latest
          name: nginx-prometheus-exporter
          args:
            - "--nginx.scrape-uri=http://localhost:8000/stub_status"
          ports:
            - name: metrics
              containerPort: 9113
      volumes:
        - name: nc
          configMap:
            name: nc