kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homework-pvc
  namespace: homework
spec:
  storageClassName: "homework-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi