---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
      - persistentvolumeclaims
      - events
      - services
      - mysqls
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for otus.homework.homework.otus/v1, Kind: MySQL
  ##
  - apiGroups:
      - otus.homework
    resources:
      - mysqls
      - mysqls/status
      - mysqls/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

