apiVersion: v1
kind: Service
metadata:
  name: homework-deployment
spec:
  selector:
    app: homework2
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer