apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx
spec:
  endpoints:
    - interval: 15s
      port: metrics
      scrapeTimeout: 14s
  selector:
    matchLabels:
      app.kubernetes.io/part-of: nginx
