apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-crb
subjects:
- kind: ServiceAccount
  name: monitoring-sa
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: ClusterRole
  name: monitoring-cr
  apiGroup: rbac.authorization.k8s.io