apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: homework-sc
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate