kafka:
  enabled: true
  controller:
    replicaCount: 1
    automountServiceAccountToken: true
  broker:
    replicaCount: 5
    persistence:
      size: 1Gi
    automountServiceAccountToken: true
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
